// <auto-generated />
namespace FinalProjectShopLaptop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatetralbev1x : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatetralbev1x));
        
        string IMigrationMetadata.Id
        {
            get { return "202007191332430_updatetralbev1x"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
